In [1]:
import pandas as pd
import sys
# NumPy is a library for advanced mathematical computation
import numpy as np

# MatPlotLib is a library for basic data visualization
import matplotlib.pyplot as plt

# SeaBorn is a library for advanced data visualization
import seaborn as sb

import glob

## General NPS Cleaning Process:
* Step 1: Import, Clean, and Aggregate Weeks 1-7 for 2016 Data
* Step 2: Import and Clean Week 8 for 2016 Data
* Step 2.5: Aggregate Weeks 1-7 with Week 8 to produce Full 2016 Dataset
* Step 3: Import and Clean 2017 Data
* Step 3.5: Aggregate Full 2016 Data with 2017 Data to produce Complete Dataset

In [2]:
PATH_DIRECTORY = "./SA_Feedback_Surveys_FINAL/2016/"
WEEK1_7_PATH = "Anon*.csv"

WEEK8_PATH = "Week 8 Feedback (2016, incomplete) - results.csv"

### Weeks 1 - 7 (2016)

In [3]:
WEEK1_7_FILES = glob.glob(PATH_DIRECTORY + WEEK1_7_PATH)

In [4]:
WEEK1_7_FILES

['./SA_Feedback_Surveys_FINAL/2016/Anon Week 7 Feedback - Taipei.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week 6 Feedback - Tokyo.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week 1 Feedback - Singapore.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week 7 Feedback - LA.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week 4 Feedback - SF.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week 5 Feedback - SV.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week 4 Feedback - SG.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week 6 Feedback - NY.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week 5 Feedback - HK.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week 1 Feedback - SF.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week 2 Feedback - LA.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week 6 Feedback - Taipei.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week 3 Feedback - NY.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week 6 Feedback - LA.csv',
 './SA_Feedback_Surveys_FINAL/2016/Anon Week

In [5]:
dfs = list()
for dataframe in WEEK1_7_FILES:
    dfs.append(pd.read_csv(dataframe))

In [6]:
dfs[0]

Timestamp  \
0   8/5/2016 1:39:41   
1   8/5/2016 1:40:47   
2   8/5/2016 1:40:50   
3   8/5/2016 1:42:44   
4   8/5/2016 1:45:13   
5   8/5/2016 1:45:39   
6   8/5/2016 1:49:21   
7   8/8/2016 1:30:34   
8   8/8/2016 1:33:45   
9   8/8/2016 1:49:29   
10  8/8/2016 1:51:00   

    How would you rate your overall satisfaction with the Summer Academy this week?  \
0                                                   3                                 
1                                                   4                                 
2                                                   4                                 
3                                                   4                                 
4                                                   5                                 
5                                                   4                                 
6                                                   4                                 
7                                                   5                                 
8                                                   5                                 
9                                                   5                                 
10                                                  3                                 

    How well is the schedule paced?  
0                                 3  
1                                 3  
2                                 3  
3                                 4  
4                                 4  
5                                 3  
6                                 3  
7                                 3  
8                                 3  
9                                 3  
10                                3

In [7]:
def get_loc_week():
    dfs = list()
    for files in WEEK1_7_FILES:
        file_split = files.split(" ")
        week = int(file_split[2])
        location = file_split[5].split(".")[0]
        df = pd.read_csv(files)
        df['week'] = week
        df['location'] = location
        dfs.append(df)
        
    return dfs

dfs = get_loc_week()

In [8]:
dfs[0]

Timestamp  \
0   8/5/2016 1:39:41   
1   8/5/2016 1:40:47   
2   8/5/2016 1:40:50   
3   8/5/2016 1:42:44   
4   8/5/2016 1:45:13   
5   8/5/2016 1:45:39   
6   8/5/2016 1:49:21   
7   8/8/2016 1:30:34   
8   8/8/2016 1:33:45   
9   8/8/2016 1:49:29   
10  8/8/2016 1:51:00   

    How would you rate your overall satisfaction with the Summer Academy this week?  \
0                                                   3                                 
1                                                   4                                 
2                                                   4                                 
3                                                   4                                 
4                                                   5                                 
5                                                   4                                 
6                                                   4                                 
7                                                   5                                 
8                                                   5                                 
9                                                   5                                 
10                                                  3                                 

    How well is the schedule paced?  week location  
0                                 3     7   Taipei  
1                                 3     7   Taipei  
2                                 3     7   Taipei  
3                                 4     7   Taipei  
4                                 4     7   Taipei  
5                                 3     7   Taipei  
6                                 3     7   Taipei  
7                                 3     7   Taipei  
8                                 3     7   Taipei  
9                                 3     7   Taipei  
10                                3     7   Taipei

### Anon Week 1 Feedback - SV.csv has  Unnamed: 0 which is actually just timestamp data
- Just need to rename to Timestamp

### Anon Week 5 Feedback - SF.csv is missing a timestamp column
- I need to add a df["Timestamp"] column and fill with np.NaN


### We want to put both 'How well are the tutorials paced?' and 'How well are the tutorials paced?' in the same dataframe and merged. Then add that column to in our main dataframe we want to create a 'pacing'column

#### Merging those two pacing columns is an example of Merging Mutually Exclusive Columns¶

### In Week 8 we need to rename our 'location' column to 'Location'

### Find dataframe with no timestamp or unnamed and add a timestamp column

In [9]:
found = None
index = None
for i, df in enumerate(dfs):
    if "Unnamed: 0" not in df.columns and "Timestamp" not in df.columns:
        df.insert(0, 'Timestamp', 'NO TIMESTAMP')
        found = df
        index = i
found

Timestamp What track are you in?  \
0   NO TIMESTAMP                   Apps   
1   NO TIMESTAMP                   Apps   
2   NO TIMESTAMP                   Apps   
3   NO TIMESTAMP                   Apps   
4   NO TIMESTAMP                   Apps   
5   NO TIMESTAMP                   Apps   
6   NO TIMESTAMP                   Apps   
7   NO TIMESTAMP                   Apps   
8   NO TIMESTAMP                   Apps   
9   NO TIMESTAMP                   Apps   
10  NO TIMESTAMP                   Apps   
11  NO TIMESTAMP                   Apps   
12  NO TIMESTAMP                   Apps   
13  NO TIMESTAMP                  Games   
14  NO TIMESTAMP                  Games   
15  NO TIMESTAMP                  Games   
16  NO TIMESTAMP                  Games   
17  NO TIMESTAMP                  Games   
18  NO TIMESTAMP                  Games   
19  NO TIMESTAMP                  Intro   
20  NO TIMESTAMP                  Intro   
21  NO TIMESTAMP                  Intro   
22  NO TIMESTAMP                  Intro   
23  NO TIMESTAMP                  Intro   
24  NO TIMESTAMP                  Intro   
25  NO TIMESTAMP                  Intro   
26  NO TIMESTAMP                  Intro   
27  NO TIMESTAMP                  Intro   
28  NO TIMESTAMP                  Intro   
29  NO TIMESTAMP                  Intro   
30  NO TIMESTAMP                  Intro   
31  NO TIMESTAMP                  Intro   
32  NO TIMESTAMP                  Intro   
33  NO TIMESTAMP                  Intro   
34  NO TIMESTAMP                  Intro   
35  NO TIMESTAMP                  Intro   
36  NO TIMESTAMP                     VR   
37  NO TIMESTAMP                     VR   
38  NO TIMESTAMP                     VR   
39  NO TIMESTAMP                     VR   
40  NO TIMESTAMP                  Intro   
41  NO TIMESTAMP                  Intro   

    How would you rate your overall satisfaction with the Summer Academy this week?  \
0                                                   3                                 
1                                                   4                                 
2                                                   4                                 
3                                                   4                                 
4                                                   3                                 
5                                                   5                                 
6                                                   3                                 
7                                                   5                                 
8                                                   1                                 
9                                                   4                                 
10                                                  5                                 
11                                                  4                                 
12                                                  3                                 
13                                                  4                                 
14                                                  5                                 
15                                                  1                                 
16                                                  5                                 
17                                                  4                                 
18                                                  5                                 
19                                                  5                                 
20                                                  4                                 
21                                                  3                                 
22                                                  5                                 
23                                                  5                

In [10]:
dfs[20] = dfs[20].rename(columns={
    'Unnamed: 0' : 'Timestamp'
})

dfs[20].head()

Timestamp What track are you in?  \
0  6/24/2016 13:32:01                  Games   
1  6/24/2016 13:48:09                   Apps   
2  6/24/2016 13:49:23                   Apps   
3  6/24/2016 13:53:25                   Apps   
4  6/24/2016 13:55:19                   Apps   

   How would you rate your overall satisfaction with the Summer Academy this week?  \
0                                                  2                                 
1                                                  3                                 
2                                                  3                                 
3                                                  3                                 
4                                                  3                                 

   How well are the tutorials paced?  week location  
0                                  4     1       SV  
1                                  4     1       SV  
2                                  3     1       SV  
3                                  5     1       SV  
4                                  3     1       SV

In [11]:
column_names = dict()

for df in dfs:
    for column in df.columns:
        if column in column_names:
            column_names[column] += 1
        else:
            column_names[column] = 1
        
column_names

{'Timestamp': 39,
 'How would you rate your overall satisfaction with the Summer Academy this week?': 39,
 'How well is the schedule paced?': 33,
 'week': 39,
 'location': 39,
 'How well are the tutorials paced?': 6,
 'What track are you in?': 24}

#### NOTES:
 - 'What track are you in?'
 - 'How well are the tutorials paced?'
 - 'How well is the schedule paced?'
 
Are all columns that are not evenly distributed across all dataframes.

In [12]:
def check_unique_vals(column_name):
    unique = set()
    for df in dfs:
        if column_name in df.columns:
            df_vals = df[column_name].unique().tolist()
            unique.update(df_vals)
    return unique

In [13]:
col_list = list(column_names.keys())

In [14]:
col_list

['Timestamp',
 'How would you rate your overall satisfaction with the Summer Academy this week?',
 'How well is the schedule paced?',
 'week',
 'location',
 'How well are the tutorials paced?',
 'What track are you in?']

In [15]:
uni_dict = dict()

for i in range(7):
    cn = col_list[i]
    uni_dict[cn] = check_unique_vals(cn)

In [16]:
uniques = list(uni_dict["How would you rate your overall satisfaction with the Summer Academy this week?"])
uniques

[1, 2, 3, 4, 5, '#REF!', '5', '4', '3']

In [17]:
sat_map = dict(zip(uniques, [1, 2, 3, 4, 5, 4, 3, 5, 0]))

sat_column = 'How would you rate your overall satisfaction with the Summer Academy this week?'

for df in dfs:
    if sat_column in df:
        df[sat_column] = df[sat_column].map(sat_map).astype(int)            


for df in dfs:
    if sat_column in df:
        print(df[sat_column].unique(), "\n\n")

[3 4 5] 


[3 4 5] 


[2 3 4 5] 


[3 5 4] 


[5 4 3] 


[4 5 3 2] 


[4 3] 


[2 4 5 3] 


[4 5] 


[3 4 5] 


[4 3 5] 


[5 4 3] 


[4 5 3] 


[5 3 1 4] 


[3 4 5 1] 


[4 3 2] 


[2 3 4 5] 


[3 5 4] 


[4 5] 


[3 4 5] 


[2 3 4 5] 


[3 4 5] 


[4 3 2 5 1] 


[4 5 3] 


[3 5 4 2] 


[5 4] 


[3 5 1 4] 


[3 4 5] 


[3 4 5] 


[4 5] 


[5 3 4] 


[5 3 4 1 2] 


[4 5 3 2] 


[5 4] 


[5 4 3] 


[2 3 4 5 1] 


[3 4 5] 


[4 3] 


[3 5 0 4] 




In [18]:
schedule_pacing_map = {
    '#REF!': 0,
    np.NaN: 0, 
    1: 1, 
    2: 2, 
    '2': 2, 
    3: 3, 
    '3': 3, 
    '4': 4, 
    4: 4, 
    5: 5, 
    '5': 5
}

for df in dfs:
    if 'How well is the schedule paced' in df:
        df['How well is the schedule paced'] = df['How well is the schedule paced'].map(schedule_pacing_map)
        df = df.drop(df[df['How well is the schedule paced'] > 0].index)

In [19]:
for df in dfs:
    if 'How would you rate your overall satisfaction with the Summer Academy this week?' in df:
        print(df['How would you rate your overall satisfaction with the Summer Academy this week?'].unique(), '\n')

[3 4 5] 

[3 4 5] 

[2 3 4 5] 

[3 5 4] 

[5 4 3] 

[4 5 3 2] 

[4 3] 

[2 4 5 3] 

[4 5] 

[3 4 5] 

[4 3 5] 

[5 4 3] 

[4 5 3] 

[5 3 1 4] 

[3 4 5 1] 

[4 3 2] 

[2 3 4 5] 

[3 5 4] 

[4 5] 

[3 4 5] 

[2 3 4 5] 

[3 4 5] 

[4 3 2 5 1] 

[4 5 3] 

[3 5 4 2] 

[5 4] 

[3 5 1 4] 

[3 4 5] 

[3 4 5] 

[4 5] 

[5 3 4] 

[5 3 4 1 2] 

[4 5 3 2] 

[5 4] 

[5 4 3] 

[2 3 4 5 1] 

[3 4 5] 

[4 3] 

[3 5 0 4] 



In [20]:
col_list

['Timestamp',
 'How would you rate your overall satisfaction with the Summer Academy this week?',
 'How well is the schedule paced?',
 'week',
 'location',
 'How well are the tutorials paced?',
 'What track are you in?']

In [21]:
unique_types = set()

for item in check_unique_vals(col_list[0]):
    unique_types.update([type(item)])
    
# unique_types
print(col_list[0], ": ", list(unique_types))

Timestamp :  [<class 'str'>, <class 'float'>]


In [22]:
def check_unique_vals(col_name):
    unique_values = set()
    for df in dfs:
        if col_name in df.columns:
            df_vals = df[col_name].unique().tolist()
            unique_values.update(df_vals)
    return unique_values

### Converting Schedule Pacing to Integers

In [23]:
shitty_df = dfs[len(dfs) - 1]

# Remove #REF! from Schedule Pacing data
shitty_df = shitty_df[shitty_df["How well is the schedule paced?"] != "#REF!"]

# Force all other Schedule Pacing data as integer data
shitty_df["How well is the schedule paced?"] = shitty_df["How well is the schedule paced?"].astype(int)

dfs[len(dfs) - 1] = shitty_df

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


In [24]:
for df in dfs:
    if "How well is the schedule paced?" in df:
        # Converts SchedulePacing to integer data
        print(df["How well is the schedule paced?"].unique())

[3 4]
[4 3 1 2 5]
[2 3 4]
[3 4 2 5]
[3 4 5 2]
[3 4]
[2 3 4 1 5]
[2 3 4]
[3 4 2]
[3 2 4]
[3 1 4]
[3 4 2 5]
[3 4 2]
[1 3 4 2 5]
[3 4]
[2 4 3]
[2 4 5 3]
[2 3 4]
[3 4]
[3 5]
[3 4 1 2 5]
[3 4 5]
[2 3 5 4]
[4 5 3 2]
[3]
[3 4]
[5 3 4 2]
[3 4 2]
[3]
[5 3 4]
[3 2 5 4]
[3 5 4]
[2 3 4 5]


In [25]:
unique_track_vals = check_unique_vals('What track are you in?')
unique_track_vals

{'Apps', 'Games', 'Intro', 'VR'}

In [26]:
def map_types_to_value(df, column_name, type_to_change, change_to_value):
    for index, item in df.iterrows():
        changer = None
        if type(item[0]) == type_to_change:
            changer = change_to_value
            return df.set_value(index, column_name, changer)

In [27]:
for df in dfs:
    map_types_to_value(df, 'Timestamp', np.nan, "NO TIMESTAMP")

unique_timestamp_vals = check_unique_vals('Timestamp')
unique_timestamp_vals

{'6/23/2016 13:17:43',
 '6/23/2016 13:19:38',
 '6/23/2016 13:19:41',
 '6/23/2016 13:19:58',
 '6/23/2016 13:21:46',
 '6/23/2016 14:44:06',
 '6/23/2016 14:48:47',
 '6/23/2016 15:55:12',
 '6/23/2016 16:11:39',
 '6/23/2016 16:14:04',
 '6/23/2016 22:07:29',
 '6/23/2016 22:09:23',
 '6/23/2016 22:11:39',
 '6/23/2016 22:11:44',
 '6/23/2016 22:13:04',
 '6/23/2016 22:13:09',
 '6/23/2016 22:13:25',
 '6/23/2016 22:15:33',
 '6/23/2016 22:24:53',
 '6/23/2016 22:41:02',
 '6/23/2016 23:56:36',
 '6/24/2016 0:18:42',
 '6/24/2016 11:05:49',
 '6/24/2016 11:34:57',
 '6/24/2016 11:37:05',
 '6/24/2016 11:40:59',
 '6/24/2016 11:41:34',
 '6/24/2016 11:41:42',
 '6/24/2016 11:41:47',
 '6/24/2016 11:42:30',
 '6/24/2016 11:46:04',
 '6/24/2016 11:47:36',
 '6/24/2016 11:53:20',
 '6/24/2016 11:53:29',
 '6/24/2016 12:58:35',
 '6/24/2016 13:05:10',
 '6/24/2016 13:07:03',
 '6/24/2016 13:07:59',
 '6/24/2016 13:09:46',
 '6/24/2016 13:11:15',
 '6/24/2016 13:16:51',
 '6/24/2016 13:18:32',
 '6/24/2016 13:20:34',
 '6/24/2016 

In [28]:
df1 = pd.DataFrame([1, 0, 3, 4, np.nan, np.nan, 0, 6, np.nan, np.nan, np.nan], columns=["a"])
df2 = pd.DataFrame([np.nan, np.nan, np.nan, np.nan, 5, 7, np.nan, np.nan, 2, 9, 8], columns=["b"])

In [29]:
df1["a"] = df1["a"].fillna(0)
df2["b"] = df2["b"].fillna(0)

In [30]:
df_final = df1['a'] + df2['b']
df_final

0     1.0
1     0.0
2     3.0
3     4.0
4     5.0
5     7.0
6     0.0
7     6.0
8     2.0
9     9.0
10    8.0
dtype: float64

In [31]:
pace_1 = 'How well is the schedule paced?'
pace_2 = 'How well are the tutorials pacecd?'

In [32]:
df_2016_week1_7 = pd.concat(dfs, ignore_index=True, sort=True)
df_2016_week1_7

How well are the tutorials paced?  How well is the schedule paced?  \
0                                  NaN                              3.0   
1                                  NaN                              3.0   
2                                  NaN                              3.0   
3                                  NaN                              4.0   
4                                  NaN                              4.0   
5                                  NaN                              3.0   
6                                  NaN                              3.0   
7                                  NaN                              3.0   
8                                  NaN                              3.0   
9                                  NaN                              3.0   
10                                 NaN                              3.0   
11                                 NaN                              4.0   
12                                 NaN                              3.0   
13                                 NaN                              1.0   
14                                 NaN                              2.0   
15                                 NaN                              4.0   
16                                 NaN                              3.0   
17                                 NaN                              5.0   
18                                 NaN                              2.0   
19                                 NaN                              4.0   
20                                 NaN                              3.0   
21                                 NaN                              3.0   
22                                 NaN                              4.0   
23                                 NaN                              3.0   
24                                 3.0                              NaN   
25                                 3.0                              NaN   
26                                 3.0                              NaN   
27                                 4.0                              NaN   
28                                 4.0                              NaN   
29                                 4.0                              NaN   
..                                 ...                              ...   
896                                NaN                              4.0   
897                                NaN                              4.0   
898                                NaN                              4.0   
899                                NaN                              4.0   
900                                NaN                              2.0   
901                                NaN                              4.0   
902                                NaN                              5.0   
903                                NaN                              3.0   
904                                NaN                              3.0   
905                                NaN                              3.0   
906                                NaN                              3.0   
907                                NaN                              3.0   
908                                NaN                              3.0   
909                                NaN                              2.0   
910                                NaN                              3.0   
911                                NaN                              3.0   
912                                NaN                              3.0   
913                                NaN                              2.0   
914                                NaN                              5.0   
915                                NaN                              4.0   
916                                NaN                              4.0   
917                           

In [33]:
type_dict = dict()

for feature in range(len(col_list)):
    unique_types = set()

    for item in check_unique_vals(col_list[feature]):
        unique_types.update([type(item)])

    type_dict[col_list[feature]] = list(unique_types)
    
type_dict

{'Timestamp': [str],
 'How would you rate your overall satisfaction with the Summer Academy this week?': [int],
 'How well is the schedule paced?': [int],
 'week': [int],
 'location': [str],
 'How well are the tutorials paced?': [int],
 'What track are you in?': [str]}

In [34]:
def map_value(df, column_name, type_to_change, change_to_value):
    for i, item in df.iterrows():
        changer = None
        if type(item[0]) == type_to_change:
            changer = change_to_value
            return df.set_value(i, column_name, changer)

In [35]:
for df in dfs:
    map_value(df, 'Timestamp', np.nan, "NO TIMESTAMP")

timestamp_vals = check_unique_vals('Timestamp')
timestamp_vals

{'6/23/2016 13:17:43',
 '6/23/2016 13:19:38',
 '6/23/2016 13:19:41',
 '6/23/2016 13:19:58',
 '6/23/2016 13:21:46',
 '6/23/2016 14:44:06',
 '6/23/2016 14:48:47',
 '6/23/2016 15:55:12',
 '6/23/2016 16:11:39',
 '6/23/2016 16:14:04',
 '6/23/2016 22:07:29',
 '6/23/2016 22:09:23',
 '6/23/2016 22:11:39',
 '6/23/2016 22:11:44',
 '6/23/2016 22:13:04',
 '6/23/2016 22:13:09',
 '6/23/2016 22:13:25',
 '6/23/2016 22:15:33',
 '6/23/2016 22:24:53',
 '6/23/2016 22:41:02',
 '6/23/2016 23:56:36',
 '6/24/2016 0:18:42',
 '6/24/2016 11:05:49',
 '6/24/2016 11:34:57',
 '6/24/2016 11:37:05',
 '6/24/2016 11:40:59',
 '6/24/2016 11:41:34',
 '6/24/2016 11:41:42',
 '6/24/2016 11:41:47',
 '6/24/2016 11:42:30',
 '6/24/2016 11:46:04',
 '6/24/2016 11:47:36',
 '6/24/2016 11:53:20',
 '6/24/2016 11:53:29',
 '6/24/2016 12:58:35',
 '6/24/2016 13:05:10',
 '6/24/2016 13:07:03',
 '6/24/2016 13:07:59',
 '6/24/2016 13:09:46',
 '6/24/2016 13:11:15',
 '6/24/2016 13:16:51',
 '6/24/2016 13:18:32',
 '6/24/2016 13:20:34',
 '6/24/2016 

In [36]:
df1 = pd.DataFrame([1, 0, 3, 4, np.nan, np.nan, 0, 6, np.nan, np.nan, np.nan], columns=["a"])
df2 = pd.DataFrame([np.nan, np.nan, np.nan, np.nan, 5, 7, np.nan, np.nan, 2, 9, 8], columns=["b"])

In [37]:
df1["a"] = df1["a"].fillna(0)
df2["b"] = df2["b"].fillna(0)

In [38]:
df_final = df1['a'] + df2['b']
df_final

0     1.0
1     0.0
2     3.0
3     4.0
4     5.0
5     7.0
6     0.0
7     6.0
8     2.0
9     9.0
10    8.0
dtype: float64

In [39]:
pace_name1 = 'How well is the schedule paced?'
pace_name2 = 'How well are the tutorials paced?'

### Merge all of 2016 week 1 through 7

In [40]:
df_2016_week_1_7 = pd.concat(dfs, ignore_index=True, sort=True)


In [41]:
df_2016_week_1_7[pace_name2] = df_2016_week_1_7[pace_name2].fillna(0)
df_2016_week_1_7[pace_name1] = df_2016_week_1_7[pace_name1].fillna(0)

df_2016_week_1_7["Pacing"] = df_2016_week_1_7[pace_name2] + df_2016_week_1_7[pace_name1]

df_2016_week_1_7.drop(columns=[pace_name2, pace_name1], inplace=True)
df_2016_week_1_7["How would you rate your overall satisfaction with the Summer Academy this week?"] = df_2016_week_1_7["How would you rate your overall satisfaction with the Summer Academy this week?"].transform(lambda x: x * 2)

df_2016_week_1_7["Year"] = "2016"

df_2016_week_1_7 = df_2016_week_1_7.rename(columns={'How would you rate your overall satisfaction with the Summer Academy this week?': 'Rating (Num)', 'What track are you in?': 'Track', 'Pacing': 'Schedule Pacing'})
# df_2016_week_1_7.drop(columns=['Timestamp'], inplace=True)

df_2016_week_1_7.head(3)

Rating (Num)         Timestamp Track location  week  Schedule Pacing  Year
0             6  8/5/2016 1:39:41   NaN   Taipei     7              3.0  2016
1             8  8/5/2016 1:40:47   NaN   Taipei     7              3.0  2016
2             8  8/5/2016 1:40:50   NaN   Taipei     7              3.0  2016

In [42]:
df["What track are you in?"] = df["What track are you in?"].fillna("Unknown")

In [43]:
df.tail()

Timestamp What track are you in?  \
31   7/8/2016 13:01:58                  Intro   
32  7/10/2016 23:44:41                  Games   
34   7/8/2016 16:41:06                   Apps   
35   7/8/2016 13:07:39                  Games   
36   7/8/2016 12:45:02                  Intro   

    How would you rate your overall satisfaction with the Summer Academy this week?  \
31                                                  5                                 
32                                                  5                                 
34                                                  3                                 
35                                                  3                                 
36                                                  3                                 

    How well is the schedule paced?  week location  
31                                4     3       SV  
32                                4     3       SV  
34                                3     3       SV  
35                                3     3       SV  
36                                3     3       SV

In [44]:
df_2016_week_1_7.columns

Index(['Rating (Num)', 'Timestamp', 'Track', 'location', 'week',
       'Schedule Pacing', 'Year'],
      dtype='object')

In [45]:
week8_df = pd.read_csv(PATH_DIRECTORY + WEEK8_PATH)

In [46]:
week8_df

#  \
0   00b836bda84e6bdbe780af97e249e59f   
1   39dde6dc0e1e375845d756fc7e39fc5f   
2   5e56b9de91670b308cb98dd2848b8739   
3   641081d05785b47a0f17448625da0d49   
4   c29bdd4f5678d78b450f4494e0f53c8c   
5   9030d8a662b39b519b2b685834413d66   
6   1c07190c7caa72bf6b59cea48e1a4a97   
7   27a63d6c24710feb52c0cfdef7e01175   
8   b47b95f84547d8347119de1da5faa46d   
9   828fafa477484f61d2ca5930fe99ad46   
10  7d70f1e30217d867f3c0f961462d8ae8   
11  65bd071ab808290560e7d11c09f56796   
12  d66976d012b4c8a5c708f1a438605488   
13  9db748a8e0d5789cb3a5fcb27fc59083   
14  5ee2a5d8e87fd5790906f7b004963e14   
15  9826290f1bf2fd4c105857e2af933ffe   
16  ea85e7c699751b5993776ef16db0b1d9   
17  58cb61ce774b116d87e3888d4c1babf1   
18  a08ef61cfa87d1ba00c691de4a55f4c2   
19  630fd265cdb8308b60b4b59351690f0a   
20  2f7303a7ac0943b341d02678b085688e   
21  785568c94d73aa0fad4493ee79fa3974   
22  fe02b118aea0ef15ccd06e6f7e6209f4   
23  6e2c750a71613e3fd7d5f425320cc750   
24  522ff7a7546272c3c98eab026e8c098a   
25  80fce9f8822690ad581ff8d554e6f629   
26  e78c696358f9c59b0375884ab9217f70   
27  4885e461415138a403fb0408a8060094   
28  bb261d3e5b4fe2197f54f28c416948e1   
29  391157a49dc832edb535b3c6ee3dd6a0   
..                               ...   
35  fa299e5db39696d38eafd4ae6e71aebb   
36  35d559a3756563f795c0e9e81299695e   
37  2a42f27c8a19a165f37439cfd9fed33d   
38  1e19d356f6f8eac878413ec736e46da8   
39  a8497fc472b7a09ac6e16e658851d652   
40  3208a7393ff3fd3c67fae17c8e48db37   
41  45d7a66a67ee79f5c9ffa6d6abb1b307   
42  964e2d8e91a04b8735e73aafedb54541   
43  e8780f8e3d0026549c276135fd9569ef   
44  864ff3fc8e19d27f3d4c46eb4b304d35   
45  c2bc67325eb91085f3686aabf309d801   
46  fd802ce8e43aa9deade38c108298dbaf   
47  ac671896bf86167dc073c3f52131fe70   
48  143652af47062192767081ff1dd630cc   
49  f4a5aed1cad9367cc58744706de54a1b   
50  3c3495614eada68b5fa8e19377e1cccd   
51  8e2309e3a1ba2a5630ea251b96712a9a   
52  44db66e47441ecd2c88dbe5dd3a38e1e   
53  80f3d539b648cfaf92b45699e7a0545b   
54  60343ca18c43feedab8481e25421484d   
55  5c99e0aac4efe9eecffd83e50ec7c8db   
56  022d99be229f86182ca1c2bc49aa2e09   
57  5a83e1056e30a8596056bec5c050a86d   
58  50f1c0545d9cef1c10be657e1083990d   
59  22ac2ab300a76178ce53104d03408c8a   
60  2d487d890a68bbdb70dd027bc1e501bb   
61  0cdf8eced1b8791ae536797c75751b25   
62  d353c2cdff6bcf3e932579a5647d511a   
63  f5716831fe432cef5da980038f2f8969   
64  951e9361c4da1756ae1c6fb2612cb9dd   

    How likely is it that you would recommend the Make School Summer Academy to a friend?  \
0                                                  10                                       
1                                                  10                                       
2                                                  10                                       
3                                                   9                                       
4                                                   3                                       
5                                                  10                                       
6                                                   8                                       
7                                                   3                                       
8                                                   6                                       
9                                                   9                                       
10                                                 10                                       
11                                                 10                                       
12                                                  8                                       
13                                                  8                                       
14                                                  8                                       
15                                                 10             

In [47]:
week8_df.rename(columns={"How likely is it that you would recommend the Make School Summer Academy to a friend?": "Rating (Num)"}, inplace=True)

In [48]:
df_2016_week_1_7["Track"] = df_2016_week_1_7["Track"].fillna("Unknown")
df_2016_week_1_7

Rating (Num)           Timestamp    Track   location  week  \
0               6    8/5/2016 1:39:41  Unknown     Taipei     7   
1               8    8/5/2016 1:40:47  Unknown     Taipei     7   
2               8    8/5/2016 1:40:50  Unknown     Taipei     7   
3               8    8/5/2016 1:42:44  Unknown     Taipei     7   
4              10    8/5/2016 1:45:13  Unknown     Taipei     7   
5               8    8/5/2016 1:45:39  Unknown     Taipei     7   
6               8    8/5/2016 1:49:21  Unknown     Taipei     7   
7              10    8/8/2016 1:30:34  Unknown     Taipei     7   
8              10    8/8/2016 1:33:45  Unknown     Taipei     7   
9              10    8/8/2016 1:49:29  Unknown     Taipei     7   
10              6    8/8/2016 1:51:00  Unknown     Taipei     7   
11              6   7/31/2016 1:04:57  Unknown      Tokyo     6   
12              8   7/31/2016 3:38:14  Unknown      Tokyo     6   
13              8   7/31/2016 3:59:43  Unknown      Tokyo     6   
14              8   7/31/2016 4:19:51  Unknown      Tokyo     6   
15             10   7/31/2016 5:14:20  Unknown      Tokyo     6   
16              6   7/31/2016 6:50:12  Unknown      Tokyo     6   
17             10  7/31/2016 15:23:52  Unknown      Tokyo     6   
18              8  7/31/2016 16:49:45  Unknown      Tokyo     6   
19              6    8/1/2016 1:18:47  Unknown      Tokyo     6   
20             10    8/1/2016 1:30:17  Unknown      Tokyo     6   
21             10    8/1/2016 1:30:17  Unknown      Tokyo     6   
22              8    8/1/2016 6:15:10  Unknown      Tokyo     6   
23              8    8/1/2016 7:56:08  Unknown      Tokyo     6   
24              4  6/23/2016 22:24:53  Unknown  Singapore     1   
25              4   6/27/2016 4:03:03  Unknown  Singapore     1   
26              6  6/23/2016 22:13:04  Unknown  Singapore     1   
27              8  6/23/2016 22:09:23  Unknown  Singapore     1   
28              8  6/23/2016 22:11:39  Unknown  Singapore     1   
29              8  6/23/2016 22:11:44  Unknown  Singapore     1   
..            ...                 ...      ...        ...   ...   
896            10   7/8/2016 14:03:46     Apps         SV     3   
897             0   7/8/2016 16:40:10     Apps         SV     3   
898            10   7/8/2016 13:58:12     Apps         SV     3   
899             0   7/8/2016 13:53:19     Apps         SV     3   
900             0   7/8/2016 15:59:30     Apps         SV     3   
901             6   7/8/2016 16:11:32     Apps         SV     3   
902             6   7/8/2016 12:49:05    Games         SV     3   
903            10   7/8/2016 12:49:16    Games         SV     3   
904             6   7/8/2016 12:47:42    Games         SV     3   
905             6   7/8/2016 12:43:44    Intro         SV     3   
906            10   7/8/2016 13:55:51     Apps         SV     3   
907             6   7/8/2016 14:02:54    Games         SV     3   
908             6   7/8/2016 14:29:22    Games         SV     3   
909             6   7/9/2016 17:05:33    Games         SV     3   
910             0   7/8/2016 16:55:21     Apps         SV     3   
911             0   7/8/2016 16:08:13    Games         SV     3   
912            10   7/8/2016 13:56:39     Apps         SV     3   
913            10   7/8/2016 14:03:35     Apps         SV     3   
914            10   7/8/2016 13:51:14    Games         SV     3   
915            10   7/8/2016 12:41:10    Intro         SV     3   
916            10   7/8/2016 12:41:13    Intro         SV     3   
917            10   7/8/2016 12:41:51    Intro         SV     3   
918            10   7/8/2016 12:43:35    Intro         SV     3   
919            10   7/8/2016 12:45:11    Intro         SV     3   
920            10   7/8/2016 12:47:39    Intro         SV     3   
921            10   7/8/2016 13:01:58    Intro         SV     3   
922            10  7/10/2016 23:44:41    Games         SV     3   
923             6   7/8/2016 16:41:06     Apps      

In [49]:
location_mapper = {
    "Taipei": "TP",
    "Tokyo": "TK",
    "Singapore": "SG",
    "TP": "TP",
    "TK": "TK",
    "LA": "LA",
    "SF": "SF",
    "SV": "SV",
    "SG": "SG",
    "NY": "NY",
    "HK": "HK"
}

df_2016_week_1_7["location"] = df_2016_week_1_7["location"].map(location_mapper)

In [50]:
df_2016_week_1_7

Rating (Num)           Timestamp    Track location  week  \
0               6    8/5/2016 1:39:41  Unknown       TP     7   
1               8    8/5/2016 1:40:47  Unknown       TP     7   
2               8    8/5/2016 1:40:50  Unknown       TP     7   
3               8    8/5/2016 1:42:44  Unknown       TP     7   
4              10    8/5/2016 1:45:13  Unknown       TP     7   
5               8    8/5/2016 1:45:39  Unknown       TP     7   
6               8    8/5/2016 1:49:21  Unknown       TP     7   
7              10    8/8/2016 1:30:34  Unknown       TP     7   
8              10    8/8/2016 1:33:45  Unknown       TP     7   
9              10    8/8/2016 1:49:29  Unknown       TP     7   
10              6    8/8/2016 1:51:00  Unknown       TP     7   
11              6   7/31/2016 1:04:57  Unknown       TK     6   
12              8   7/31/2016 3:38:14  Unknown       TK     6   
13              8   7/31/2016 3:59:43  Unknown       TK     6   
14              8   7/31/2016 4:19:51  Unknown       TK     6   
15             10   7/31/2016 5:14:20  Unknown       TK     6   
16              6   7/31/2016 6:50:12  Unknown       TK     6   
17             10  7/31/2016 15:23:52  Unknown       TK     6   
18              8  7/31/2016 16:49:45  Unknown       TK     6   
19              6    8/1/2016 1:18:47  Unknown       TK     6   
20             10    8/1/2016 1:30:17  Unknown       TK     6   
21             10    8/1/2016 1:30:17  Unknown       TK     6   
22              8    8/1/2016 6:15:10  Unknown       TK     6   
23              8    8/1/2016 7:56:08  Unknown       TK     6   
24              4  6/23/2016 22:24:53  Unknown       SG     1   
25              4   6/27/2016 4:03:03  Unknown       SG     1   
26              6  6/23/2016 22:13:04  Unknown       SG     1   
27              8  6/23/2016 22:09:23  Unknown       SG     1   
28              8  6/23/2016 22:11:39  Unknown       SG     1   
29              8  6/23/2016 22:11:44  Unknown       SG     1   
..            ...                 ...      ...      ...   ...   
896            10   7/8/2016 14:03:46     Apps       SV     3   
897             0   7/8/2016 16:40:10     Apps       SV     3   
898            10   7/8/2016 13:58:12     Apps       SV     3   
899             0   7/8/2016 13:53:19     Apps       SV     3   
900             0   7/8/2016 15:59:30     Apps       SV     3   
901             6   7/8/2016 16:11:32     Apps       SV     3   
902             6   7/8/2016 12:49:05    Games       SV     3   
903            10   7/8/2016 12:49:16    Games       SV     3   
904             6   7/8/2016 12:47:42    Games       SV     3   
905             6   7/8/2016 12:43:44    Intro       SV     3   
906            10   7/8/2016 13:55:51     Apps       SV     3   
907             6   7/8/2016 14:02:54    Games       SV     3   
908             6   7/8/2016 14:29:22    Games       SV     3   
909             6   7/9/2016 17:05:33    Games       SV     3   
910             0   7/8/2016 16:55:21     Apps       SV     3   
911             0   7/8/2016 16:08:13    Games       SV     3   
912            10   7/8/2016 13:56:39     Apps       SV     3   
913            10   7/8/2016 14:03:35     Apps       SV     3   
914            10   7/8/2016 13:51:14    Games       SV     3   
915            10   7/8/2016 12:41:10    Intro       SV     3   
916            10   7/8/2016 12:41:13    Intro       SV     3   
917            10   7/8/2016 12:41:51    Intro       SV     3   
918            10   7/8/2016 12:43:35    Intro       SV     3   
919            10   7/8/2016 12:45:11    Intro       SV     3   
920            10   7/8/2016 12:47:39    Intro       SV     3   
921            10   7/8/2016 13:01:58    Intro       SV     3   
922            10  7/10/2016 23:44:41    Games       SV     3   
923             6   7/8/2016 16:41:06     Apps       SV     3   
924             6   7/8/2016 13:07:39    Games       SV     3   
925             6   7/8/2016 12:45:02   

# `CHECKPOINT`: Saving Weeks 1-7

## Cleaning week 8

In [51]:
week8_df

#  Rating (Num)       location  \
0   00b836bda84e6bdbe780af97e249e59f            10       New York   
1   39dde6dc0e1e375845d756fc7e39fc5f            10  San Francisco   
2   5e56b9de91670b308cb98dd2848b8739            10       New York   
3   641081d05785b47a0f17448625da0d49             9      Sunnyvale   
4   c29bdd4f5678d78b450f4494e0f53c8c             3  San Francisco   
5   9030d8a662b39b519b2b685834413d66            10  San Francisco   
6   1c07190c7caa72bf6b59cea48e1a4a97             8  San Francisco   
7   27a63d6c24710feb52c0cfdef7e01175             3       New York   
8   b47b95f84547d8347119de1da5faa46d             6      Singapore   
9   828fafa477484f61d2ca5930fe99ad46             9       New York   
10  7d70f1e30217d867f3c0f961462d8ae8            10      Sunnyvale   
11  65bd071ab808290560e7d11c09f56796            10  San Francisco   
12  d66976d012b4c8a5c708f1a438605488             8  San Francisco   
13  9db748a8e0d5789cb3a5fcb27fc59083             8      Sunnyvale   
14  5ee2a5d8e87fd5790906f7b004963e14             8    Los Angeles   
15  9826290f1bf2fd4c105857e2af933ffe            10  San Francisco   
16  ea85e7c699751b5993776ef16db0b1d9             9      Sunnyvale   
17  58cb61ce774b116d87e3888d4c1babf1            10       New York   
18  a08ef61cfa87d1ba00c691de4a55f4c2             7      Singapore   
19  630fd265cdb8308b60b4b59351690f0a            10  San Francisco   
20  2f7303a7ac0943b341d02678b085688e            10  San Francisco   
21  785568c94d73aa0fad4493ee79fa3974            10      Sunnyvale   
22  fe02b118aea0ef15ccd06e6f7e6209f4             4       New York   
23  6e2c750a71613e3fd7d5f425320cc750             9  San Francisco   
24  522ff7a7546272c3c98eab026e8c098a            10      Sunnyvale   
25  80fce9f8822690ad581ff8d554e6f629             9      Sunnyvale   
26  e78c696358f9c59b0375884ab9217f70            10  San Francisco   
27  4885e461415138a403fb0408a8060094            10      Sunnyvale   
28  bb261d3e5b4fe2197f54f28c416948e1             7      Sunnyvale   
29  391157a49dc832edb535b3c6ee3dd6a0            10  San Francisco   
..                               ...           ...            ...   
35  fa299e5db39696d38eafd4ae6e71aebb             9      Singapore   
36  35d559a3756563f795c0e9e81299695e            10  San Francisco   
37  2a42f27c8a19a165f37439cfd9fed33d            10       New York   
38  1e19d356f6f8eac878413ec736e46da8             9  San Francisco   
39  a8497fc472b7a09ac6e16e658851d652            10       New York   
40  3208a7393ff3fd3c67fae17c8e48db37             8      Sunnyvale   
41  45d7a66a67ee79f5c9ffa6d6abb1b307            10  San Francisco   
42  964e2d8e91a04b8735e73aafedb54541             9  San Francisco   
43  e8780f8e3d0026549c276135fd9569ef             7       New York   
44  864ff3fc8e19d27f3d4c46eb4b304d35            10  San Francisco   
45  c2bc67325eb91085f3686aabf309d801            10    Los Angeles   
46  fd802ce8e43aa9deade38c108298dbaf            10      Sunnyvale   
47  ac671896bf86167dc073c3f52131fe70             8       New York   
48  143652af47062192767081ff1dd630cc            10  San Francisco   
49  f4a5aed1cad9367cc58744706de54a1b             7      Sunnyvale   
50  3c3495614eada68b5fa8e19377e1cccd            10    Los Angeles   
51  8e2309e3a1ba2a5630ea251b96712a9a             8  San Francisco   
52  44db66e47441ecd2c88dbe5dd3a38e1e             8       New York   
53  80f3d539b648cfaf92b45699e7a0545b            10  San Francisco   
54  60343ca18c43feedab8481e25421484d             7  San Francisco   
55  5c99e0aac4efe9eecffd83e50ec7c8db             7  San Francisco   
56  022d99be229f86182ca1c2bc49aa2e09            10  San Francisco   
57  5a83e1056e30a8596056bec5c050a86d             9  San Francisco   
58  50f1c0545d9cef1c10be657e1083990d            10       New York   
59  22ac2ab300a76178ce53104d03408c8a             8  San Francisco   
60  2d487d890a68bbdb70dd027bc1e501bb             9  San Francisco   
61  0cdf8eced1b8791ae536797c75751

In [52]:
week8_df.drop(columns=['Network ID', '#'], inplace=True)

In [53]:
week8_df.location.unique()

array(['New York', 'San Francisco', 'Sunnyvale', 'Singapore',
       'Los Angeles'], dtype=object)

In [54]:
location_mapper = {
    'New York': 'NY',
    'San Francisco' : 'SF',
    'Sunnyvale': 'SV',
    'Singapore': 'SG',
    'Los Angeles': 'LA',
    'LA':'LA',
    'NY': 'NY',
    'SF':'SF',
    'SV': 'SV',
    'SG':'SG'
}

week8_df["location"] = week8_df["location"].map(location_mapper)

In [55]:
week8_df.head()

Rating (Num) location                track Start Date (UTC)  \
0            10       NY           summerApps      9/7/16 1:03   
1            10       SF          summerIntro      9/7/16 1:03   
2            10       NY          summerIntro      9/7/16 1:03   
3             9       SV  summerApps (4-week)      9/7/16 1:04   
4             3       SF          summerIntro      9/7/16 1:04   

  Submit Date (UTC)  
0       9/7/16 1:04  
1       9/7/16 1:04  
2       9/7/16 1:05  
3       9/7/16 1:06  
4       9/7/16 1:11

In [56]:
week8_df["week"] = 8

In [57]:
len(week8_df[week8_df["track"] == "summerApps (4-week)"])

3

In [58]:
week8_df.track.unique()

array(['summerApps', 'summerIntro', 'summerApps (4-week)', 'summerGames',
       'summerVR', 'summerGames (4-week)'], dtype=object)

In [59]:
track_mapper = {
    'summerApps': 'Apps',
    'summerIntro': 'Intro',
    'summerApps (4-week)': 'Apps',
    'summerGames': 'Games',
    'summerGames (4-week)' : 'Games',
    'summerVR': 'VR',
    'Apps': 'Apps',
    'Intro': 'Intro',
    'Games': 'Games',
    'VR': 'VR'
}

week8_df["track"] = week8_df["track"].map(track_mapper)

In [60]:
week8_df['track'].unique()

array(['Apps', 'Intro', 'Games', 'VR'], dtype=object)

In [61]:
week8_df

Rating (Num) location  track Start Date (UTC) Submit Date (UTC)  week
0             10       NY   Apps      9/7/16 1:03       9/7/16 1:04     8
1             10       SF  Intro      9/7/16 1:03       9/7/16 1:04     8
2             10       NY  Intro      9/7/16 1:03       9/7/16 1:05     8
3              9       SV   Apps      9/7/16 1:04       9/7/16 1:06     8
4              3       SF  Intro      9/7/16 1:04       9/7/16 1:11     8
5             10       SF   Apps      9/7/16 1:09       9/7/16 1:13     8
6              8       SF   Apps      9/7/16 1:04       9/7/16 1:14     8
7              3       NY  Games      9/7/16 1:14       9/7/16 1:15     8
8              6       SG   Apps      9/7/16 1:16       9/7/16 1:21     8
9              9       NY  Games      9/7/16 1:22       9/7/16 1:27     8
10            10       SV  Games      9/7/16 1:28       9/7/16 1:29     8
11            10       SF     VR      9/7/16 1:22       9/7/16 1:33     8
12             8       SF  Intro      9/7/16 1:30       9/7/16 1:36     8
13             8       SV   Apps      9/7/16 1:47       9/7/16 1:50     8
14             8       LA  Games      9/7/16 1:34       9/7/16 1:51     8
15            10       SF   Apps      9/7/16 2:28       9/7/16 2:33     8
16             9       SV  Games      9/7/16 2:39       9/7/16 2:41     8
17            10       NY  Games      9/7/16 2:39       9/7/16 2:43     8
18             7       SG   Apps      9/7/16 2:47       9/7/16 2:50     8
19            10       SF  Intro      9/7/16 2:56       9/7/16 2:56     8
20            10       SF   Apps      9/7/16 2:58       9/7/16 2:59     8
21            10       SV  Games      9/7/16 2:59       9/7/16 3:01     8
22             4       NY  Intro      9/7/16 3:05       9/7/16 3:08     8
23             9       SF  Games      9/7/16 3:22       9/7/16 3:31     8
24            10       SV  Games      9/7/16 3:15       9/7/16 3:31     8
25             9       SV   Apps      9/7/16 3:41       9/7/16 3:42     8
26            10       SF  Intro      9/7/16 4:04       9/7/16 4:05     8
27            10       SV   Apps      9/7/16 4:07       9/7/16 4:10     8
28             7       SV  Games      9/7/16 4:20       9/7/16 4:21     8
29            10       SF  Games      9/7/16 5:41       9/7/16 5:43     8
..           ...      ...    ...              ...               ...   ...
35             9       SG   Apps     9/7/16 12:26      9/7/16 12:26     8
36            10       SF   Apps     9/7/16 12:45      9/7/16 12:48     8
37            10       NY  Intro     9/7/16 13:09      9/7/16 13:10     8
38             9       SF   Apps     9/7/16 14:39      9/7/16 14:40     8
39            10       NY   Apps     9/7/16 14:52      9/7/16 14:54     8
40             8       SV   Apps     9/7/16 15:57      9/7/16 15:58     8
41            10       SF   Apps     9/7/16 17:11      9/7/16 17:21     8
42             9       SF     VR     9/7/16 19:13      9/7/16 19:25     8
43             7       NY   Apps     9/7/16 19:23      9/7/16 19:26     8
44            10       SF   Apps     9/7/16 19:39      9/7/16 19:40     8
45            10       LA  Games     9/7/16 19:51      9/7/16 19:57     8
46            10       SV  Intro     9/7/16 23:58       9/8/16 0:00     8
47             8       NY   Apps      9/8/16 0:50       9/8/16 0:58     8
48            10       SF  Games      9/8/16 1:55       9/8/16 1:59     8
49             7       SV   Apps      9/8/16 5:59       9/8/16 6:04     8
50            10       LA  Games     9/8/16 14:25      9/8/16 14:27     8
51             8       SF  Games     9/8/16 22:00      9/8/16 22:06     8
52             8       NY   Apps     9/8/16 22:16      9/8/16 22:20     8
53            10       SF   Apps     9/8/16 23:06      9/8/16 23:07     8
54             7       SF   Apps     9/8/16 23:01      9/8/16 23:11     8
55             7       SF  Intro      9/9/16 1:41       9/9/16 1:42     8
56            10       SF  Intro      9/9/16 4:22       9/9/16 4:25     8
57      

In [62]:
week8_df.head(3)

Rating (Num) location  track Start Date (UTC) Submit Date (UTC)  week
0            10       NY   Apps      9/7/16 1:03       9/7/16 1:04     8
1            10       SF  Intro      9/7/16 1:03       9/7/16 1:04     8
2            10       NY  Intro      9/7/16 1:03       9/7/16 1:05     8

In [63]:
# week8_df.drop(columns=['Network ID', '#'], inplace=True)
week8_df.drop(columns=['Start Date (UTC)'], inplace=True)

In [64]:
week8_df

Rating (Num) location  track Submit Date (UTC)  week
0             10       NY   Apps       9/7/16 1:04     8
1             10       SF  Intro       9/7/16 1:04     8
2             10       NY  Intro       9/7/16 1:05     8
3              9       SV   Apps       9/7/16 1:06     8
4              3       SF  Intro       9/7/16 1:11     8
5             10       SF   Apps       9/7/16 1:13     8
6              8       SF   Apps       9/7/16 1:14     8
7              3       NY  Games       9/7/16 1:15     8
8              6       SG   Apps       9/7/16 1:21     8
9              9       NY  Games       9/7/16 1:27     8
10            10       SV  Games       9/7/16 1:29     8
11            10       SF     VR       9/7/16 1:33     8
12             8       SF  Intro       9/7/16 1:36     8
13             8       SV   Apps       9/7/16 1:50     8
14             8       LA  Games       9/7/16 1:51     8
15            10       SF   Apps       9/7/16 2:33     8
16             9       SV  Games       9/7/16 2:41     8
17            10       NY  Games       9/7/16 2:43     8
18             7       SG   Apps       9/7/16 2:50     8
19            10       SF  Intro       9/7/16 2:56     8
20            10       SF   Apps       9/7/16 2:59     8
21            10       SV  Games       9/7/16 3:01     8
22             4       NY  Intro       9/7/16 3:08     8
23             9       SF  Games       9/7/16 3:31     8
24            10       SV  Games       9/7/16 3:31     8
25             9       SV   Apps       9/7/16 3:42     8
26            10       SF  Intro       9/7/16 4:05     8
27            10       SV   Apps       9/7/16 4:10     8
28             7       SV  Games       9/7/16 4:21     8
29            10       SF  Games       9/7/16 5:43     8
..           ...      ...    ...               ...   ...
35             9       SG   Apps      9/7/16 12:26     8
36            10       SF   Apps      9/7/16 12:48     8
37            10       NY  Intro      9/7/16 13:10     8
38             9       SF   Apps      9/7/16 14:40     8
39            10       NY   Apps      9/7/16 14:54     8
40             8       SV   Apps      9/7/16 15:58     8
41            10       SF   Apps      9/7/16 17:21     8
42             9       SF     VR      9/7/16 19:25     8
43             7       NY   Apps      9/7/16 19:26     8
44            10       SF   Apps      9/7/16 19:40     8
45            10       LA  Games      9/7/16 19:57     8
46            10       SV  Intro       9/8/16 0:00     8
47             8       NY   Apps       9/8/16 0:58     8
48            10       SF  Games       9/8/16 1:59     8
49             7       SV   Apps       9/8/16 6:04     8
50            10       LA  Games      9/8/16 14:27     8
51             8       SF  Games      9/8/16 22:06     8
52             8       NY   Apps      9/8/16 22:20     8
53            10       SF   Apps      9/8/16 23:07     8
54             7       SF   Apps      9/8/16 23:11     8
55             7       SF  Intro       9/9/16 1:42     8
56            10       SF  Intro       9/9/16 4:25     8
57             9       SF   Apps      9/9/16 11:09     8
58            10       NY  Games      9/9/16 13:28     8
59             8       SF  Games     9/10/16 22:30     8
60             9       SF   Apps      9/12/16 0:13     8
61             5       SF     VR      9/13/16 4:42     8
62            10       SF  Games     9/13/16 20:13     8
63             9       SF  Intro     9/14/16 12:10     8
64             9       SV  Games     9/26/16 16:34     8

[65 rows x 5 columns]

In [65]:
week8_df.rename(index=str, columns={"Submit Date (UTC)": "Timestamp", "track": "Track"}, inplace=True)

In [66]:
week8_df['Year'] = 2016

In [67]:
week8_df

Rating (Num) location  Track      Timestamp  week  Year
0             10       NY   Apps    9/7/16 1:04     8  2016
1             10       SF  Intro    9/7/16 1:04     8  2016
2             10       NY  Intro    9/7/16 1:05     8  2016
3              9       SV   Apps    9/7/16 1:06     8  2016
4              3       SF  Intro    9/7/16 1:11     8  2016
5             10       SF   Apps    9/7/16 1:13     8  2016
6              8       SF   Apps    9/7/16 1:14     8  2016
7              3       NY  Games    9/7/16 1:15     8  2016
8              6       SG   Apps    9/7/16 1:21     8  2016
9              9       NY  Games    9/7/16 1:27     8  2016
10            10       SV  Games    9/7/16 1:29     8  2016
11            10       SF     VR    9/7/16 1:33     8  2016
12             8       SF  Intro    9/7/16 1:36     8  2016
13             8       SV   Apps    9/7/16 1:50     8  2016
14             8       LA  Games    9/7/16 1:51     8  2016
15            10       SF   Apps    9/7/16 2:33     8  2016
16             9       SV  Games    9/7/16 2:41     8  2016
17            10       NY  Games    9/7/16 2:43     8  2016
18             7       SG   Apps    9/7/16 2:50     8  2016
19            10       SF  Intro    9/7/16 2:56     8  2016
20            10       SF   Apps    9/7/16 2:59     8  2016
21            10       SV  Games    9/7/16 3:01     8  2016
22             4       NY  Intro    9/7/16 3:08     8  2016
23             9       SF  Games    9/7/16 3:31     8  2016
24            10       SV  Games    9/7/16 3:31     8  2016
25             9       SV   Apps    9/7/16 3:42     8  2016
26            10       SF  Intro    9/7/16 4:05     8  2016
27            10       SV   Apps    9/7/16 4:10     8  2016
28             7       SV  Games    9/7/16 4:21     8  2016
29            10       SF  Games    9/7/16 5:43     8  2016
..           ...      ...    ...            ...   ...   ...
35             9       SG   Apps   9/7/16 12:26     8  2016
36            10       SF   Apps   9/7/16 12:48     8  2016
37            10       NY  Intro   9/7/16 13:10     8  2016
38             9       SF   Apps   9/7/16 14:40     8  2016
39            10       NY   Apps   9/7/16 14:54     8  2016
40             8       SV   Apps   9/7/16 15:58     8  2016
41            10       SF   Apps   9/7/16 17:21     8  2016
42             9       SF     VR   9/7/16 19:25     8  2016
43             7       NY   Apps   9/7/16 19:26     8  2016
44            10       SF   Apps   9/7/16 19:40     8  2016
45            10       LA  Games   9/7/16 19:57     8  2016
46            10       SV  Intro    9/8/16 0:00     8  2016
47             8       NY   Apps    9/8/16 0:58     8  2016
48            10       SF  Games    9/8/16 1:59     8  2016
49             7       SV   Apps    9/8/16 6:04     8  2016
50            10       LA  Games   9/8/16 14:27     8  2016
51             8       SF  Games   9/8/16 22:06     8  2016
52             8       NY   Apps   9/8/16 22:20     8  2016
53            10       SF   Apps   9/8/16 23:07     8  2016
54             7       SF   Apps   9/8/16 23:11     8  2016
55             7       SF  Intro    9/9/16 1:42     8  2016
56            10       SF  Intro    9/9/16 4:25     8  2016
57             9       SF   Apps   9/9/16 11:09     8  2016
58            10       NY  Games   9/9/16 13:28     8  2016
59             8       SF  Games  9/10/16 22:30     8  2016
60             9       SF   Apps   9/12/16 0:13     8  2016
61             5       SF     VR   9/13/16 4:42     8  2016
62            10       SF  Games  9/13/16 20:13     8  2016
63             9       SF  Intro  9/14/16 12:10     8  2016
64             9       SV  Games  9/26/16 16:34     8  2016

[65 rows x 6 columns]

In [68]:
df_2016_week_1_7.columns

Index(['Rating (Num)', 'Timestamp', 'Track', 'location', 'week',
       'Schedule Pacing', 'Year'],
      dtype='object')

In [69]:
df_2016_week_1_7['Schedule Pacing'].unique()

array([3., 4., 1., 2., 5.])

In [70]:
week8_df['Schedule Pacing'] = 0.0

In [71]:
week8_df

Rating (Num) location  Track      Timestamp  week  Year  Schedule Pacing
0             10       NY   Apps    9/7/16 1:04     8  2016              0.0
1             10       SF  Intro    9/7/16 1:04     8  2016              0.0
2             10       NY  Intro    9/7/16 1:05     8  2016              0.0
3              9       SV   Apps    9/7/16 1:06     8  2016              0.0
4              3       SF  Intro    9/7/16 1:11     8  2016              0.0
5             10       SF   Apps    9/7/16 1:13     8  2016              0.0
6              8       SF   Apps    9/7/16 1:14     8  2016              0.0
7              3       NY  Games    9/7/16 1:15     8  2016              0.0
8              6       SG   Apps    9/7/16 1:21     8  2016              0.0
9              9       NY  Games    9/7/16 1:27     8  2016              0.0
10            10       SV  Games    9/7/16 1:29     8  2016              0.0
11            10       SF     VR    9/7/16 1:33     8  2016              0.0
12             8       SF  Intro    9/7/16 1:36     8  2016              0.0
13             8       SV   Apps    9/7/16 1:50     8  2016              0.0
14             8       LA  Games    9/7/16 1:51     8  2016              0.0
15            10       SF   Apps    9/7/16 2:33     8  2016              0.0
16             9       SV  Games    9/7/16 2:41     8  2016              0.0
17            10       NY  Games    9/7/16 2:43     8  2016              0.0
18             7       SG   Apps    9/7/16 2:50     8  2016              0.0
19            10       SF  Intro    9/7/16 2:56     8  2016              0.0
20            10       SF   Apps    9/7/16 2:59     8  2016              0.0
21            10       SV  Games    9/7/16 3:01     8  2016              0.0
22             4       NY  Intro    9/7/16 3:08     8  2016              0.0
23             9       SF  Games    9/7/16 3:31     8  2016              0.0
24            10       SV  Games    9/7/16 3:31     8  2016              0.0
25             9       SV   Apps    9/7/16 3:42     8  2016              0.0
26            10       SF  Intro    9/7/16 4:05     8  2016              0.0
27            10       SV   Apps    9/7/16 4:10     8  2016              0.0
28             7       SV  Games    9/7/16 4:21     8  2016              0.0
29            10       SF  Games    9/7/16 5:43     8  2016              0.0
..           ...      ...    ...            ...   ...   ...              ...
35             9       SG   Apps   9/7/16 12:26     8  2016              0.0
36            10       SF   Apps   9/7/16 12:48     8  2016              0.0
37            10       NY  Intro   9/7/16 13:10     8  2016              0.0
38             9       SF   Apps   9/7/16 14:40     8  2016              0.0
39            10       NY   Apps   9/7/16 14:54     8  2016              0.0
40             8       SV   Apps   9/7/16 15:58     8  2016              0.0
41            10       SF   Apps   9/7/16 17:21     8  2016              0.0
42             9       SF     VR   9/7/16 19:25     8  2016              0.0
43             7       NY   Apps   9/7/16 19:26     8  2016              0.0
44            10       SF   Apps   9/7/16 19:40     8  2016              0.0
45            10       LA  Games   9/7/16 19:57     8  2016              0.0
46            10       SV  Intro    9/8/16 0:00     8  2016              0.0
47             8       NY   Apps    9/8/16 0:58     8  2016              0.0
48            10       SF  Games    9/8/16 1:59     8  2016              0.0
49             7       SV   Apps    9/8/16 6:04     8  2016              0.0
50            10       LA  Games   9/8/16 14:27     8  2016              0.0
51             8       SF  Games   9/8/16 22:06     8  2016              0.0
52             8       NY   Apps   9/8/16 22:20     8  2016              0.0
53            10       SF   Apps   9/8/16 23:07     8  2016              0.0
54             7       SF   Apps   9/8/16 23:11     8  2016              0.0


In [72]:
len(df_2016_week_1_7.columns) == len(week8_df.columns)

True

In [73]:
week8_df.rename(index=str, columns={"Rating (Num)": "Satisfaction Score"}, inplace=True)
df_2016_week_1_7.rename(index=str, columns={"Rating (Num)": "Satisfaction Score"}, inplace=True)

In [74]:
week8_df

Satisfaction Score location  Track      Timestamp  week  Year  \
0                   10       NY   Apps    9/7/16 1:04     8  2016   
1                   10       SF  Intro    9/7/16 1:04     8  2016   
2                   10       NY  Intro    9/7/16 1:05     8  2016   
3                    9       SV   Apps    9/7/16 1:06     8  2016   
4                    3       SF  Intro    9/7/16 1:11     8  2016   
5                   10       SF   Apps    9/7/16 1:13     8  2016   
6                    8       SF   Apps    9/7/16 1:14     8  2016   
7                    3       NY  Games    9/7/16 1:15     8  2016   
8                    6       SG   Apps    9/7/16 1:21     8  2016   
9                    9       NY  Games    9/7/16 1:27     8  2016   
10                  10       SV  Games    9/7/16 1:29     8  2016   
11                  10       SF     VR    9/7/16 1:33     8  2016   
12                   8       SF  Intro    9/7/16 1:36     8  2016   
13                   8       SV   Apps    9/7/16 1:50     8  2016   
14                   8       LA  Games    9/7/16 1:51     8  2016   
15                  10       SF   Apps    9/7/16 2:33     8  2016   
16                   9       SV  Games    9/7/16 2:41     8  2016   
17                  10       NY  Games    9/7/16 2:43     8  2016   
18                   7       SG   Apps    9/7/16 2:50     8  2016   
19                  10       SF  Intro    9/7/16 2:56     8  2016   
20                  10       SF   Apps    9/7/16 2:59     8  2016   
21                  10       SV  Games    9/7/16 3:01     8  2016   
22                   4       NY  Intro    9/7/16 3:08     8  2016   
23                   9       SF  Games    9/7/16 3:31     8  2016   
24                  10       SV  Games    9/7/16 3:31     8  2016   
25                   9       SV   Apps    9/7/16 3:42     8  2016   
26                  10       SF  Intro    9/7/16 4:05     8  2016   
27                  10       SV   Apps    9/7/16 4:10     8  2016   
28                   7       SV  Games    9/7/16 4:21     8  2016   
29                  10       SF  Games    9/7/16 5:43     8  2016   
..                 ...      ...    ...            ...   ...   ...   
35                   9       SG   Apps   9/7/16 12:26     8  2016   
36                  10       SF   Apps   9/7/16 12:48     8  2016   
37                  10       NY  Intro   9/7/16 13:10     8  2016   
38                   9       SF   Apps   9/7/16 14:40     8  2016   
39                  10       NY   Apps   9/7/16 14:54     8  2016   
40                   8       SV   Apps   9/7/16 15:58     8  2016   
41                  10       SF   Apps   9/7/16 17:21     8  2016   
42                   9       SF     VR   9/7/16 19:25     8  2016   
43                   7       NY   Apps   9/7/16 19:26     8  2016   
44                  10       SF   Apps   9/7/16 19:40     8  2016   
45                  10       LA  Games   9/7/16 19:57     8  2016   
46                  10       SV  Intro    9/8/16 0:00     8  2016   
47                   8       NY   Apps    9/8/16 0:58     8  2016   
48                  10       SF  Games    9/8/16 1:59     8  2016   
49                   7       SV   Apps    9/8/16 6:04     8  2016   
50                  10       LA  Games   9/8/16 14:27     8  2016   
51                   8       SF  Games   9/8/16 22:06     8  2016   
52                   8       NY   Apps   9/8/16 22:20     8  2016   
53                  10       SF   Apps   9/8/16 23:07     8  2016   
54                   7       SF   Apps   9/8/16 23:11     8  2016   
55                   7       SF  Intro    9/9/16 1:42     8  2016   
56                  10       SF  Intro    9/9/16 4:25     8  2016   
57                   9       SF   Apps   9/9/16 11:09     8  2016   
58                  10       NY  Games   9/9/16 13:28     8  2016   
59                   8       SF  Games  9/10/16 22:30     8  2016   
60                   9       SF   Apps   9/12/16 0:13     8  2016   
61

In [75]:
df_2016_week_1_7

Satisfaction Score           Timestamp    Track location  week  \
0                     6    8/5/2016 1:39:41  Unknown       TP     7   
1                     8    8/5/2016 1:40:47  Unknown       TP     7   
2                     8    8/5/2016 1:40:50  Unknown       TP     7   
3                     8    8/5/2016 1:42:44  Unknown       TP     7   
4                    10    8/5/2016 1:45:13  Unknown       TP     7   
5                     8    8/5/2016 1:45:39  Unknown       TP     7   
6                     8    8/5/2016 1:49:21  Unknown       TP     7   
7                    10    8/8/2016 1:30:34  Unknown       TP     7   
8                    10    8/8/2016 1:33:45  Unknown       TP     7   
9                    10    8/8/2016 1:49:29  Unknown       TP     7   
10                    6    8/8/2016 1:51:00  Unknown       TP     7   
11                    6   7/31/2016 1:04:57  Unknown       TK     6   
12                    8   7/31/2016 3:38:14  Unknown       TK     6   
13                    8   7/31/2016 3:59:43  Unknown       TK     6   
14                    8   7/31/2016 4:19:51  Unknown       TK     6   
15                   10   7/31/2016 5:14:20  Unknown       TK     6   
16                    6   7/31/2016 6:50:12  Unknown       TK     6   
17                   10  7/31/2016 15:23:52  Unknown       TK     6   
18                    8  7/31/2016 16:49:45  Unknown       TK     6   
19                    6    8/1/2016 1:18:47  Unknown       TK     6   
20                   10    8/1/2016 1:30:17  Unknown       TK     6   
21                   10    8/1/2016 1:30:17  Unknown       TK     6   
22                    8    8/1/2016 6:15:10  Unknown       TK     6   
23                    8    8/1/2016 7:56:08  Unknown       TK     6   
24                    4  6/23/2016 22:24:53  Unknown       SG     1   
25                    4   6/27/2016 4:03:03  Unknown       SG     1   
26                    6  6/23/2016 22:13:04  Unknown       SG     1   
27                    8  6/23/2016 22:09:23  Unknown       SG     1   
28                    8  6/23/2016 22:11:39  Unknown       SG     1   
29                    8  6/23/2016 22:11:44  Unknown       SG     1   
..                  ...                 ...      ...      ...   ...   
896                  10   7/8/2016 14:03:46     Apps       SV     3   
897                   0   7/8/2016 16:40:10     Apps       SV     3   
898                  10   7/8/2016 13:58:12     Apps       SV     3   
899                   0   7/8/2016 13:53:19     Apps       SV     3   
900                   0   7/8/2016 15:59:30     Apps       SV     3   
901                   6   7/8/2016 16:11:32     Apps       SV     3   
902                   6   7/8/2016 12:49:05    Games       SV     3   
903                  10   7/8/2016 12:49:16    Games       SV     3   
904                   6   7/8/2016 12:47:42    Games       SV     3   
905                   6   7/8/2016 12:43:44    Intro       SV     3   
906                  10   7/8/2016 13:55:51     Apps       SV     3   
907                   6   7/8/2016 14:02:54    Games       SV     3   
908                   6   7/8/2016 14:29:22    Games       SV     3   
909                   6   7/9/2016 17:05:33    Games       SV     3   
910                   0   7/8/2016 16:55:21     Apps       SV     3   
911                   0   7/8/2016 16:08:13    Games       SV     3   
912                  10   7/8/2016 13:56:39     Apps       SV     3   
913                  10   7/8/2016 14:03:35     Apps       SV     3   
914                  10   7/8/2016 13:51:14    Games       SV     3   
915                  10   7/8/2016 12:41:10    Intro       SV     3   
916                  10   7/8/2016 12:41:13    Intro       SV     3   
917                  10   7/8/2016 12:41:51    Intro       SV     3   
918                  10   7/8/2016 12:43:35    Intro       SV     3   
919                  10   7/8/2016 12:45:11    Intro       SV     3   
920                  10   7/8

In [76]:
final_df = pd.concat([df_2016_week_1_7, week8_df], ignore_index=True, sort=True)

In [77]:
final_df

Satisfaction Score  Schedule Pacing           Timestamp    Track  Year  \
0                     6              3.0    8/5/2016 1:39:41  Unknown  2016   
1                     8              3.0    8/5/2016 1:40:47  Unknown  2016   
2                     8              3.0    8/5/2016 1:40:50  Unknown  2016   
3                     8              4.0    8/5/2016 1:42:44  Unknown  2016   
4                    10              4.0    8/5/2016 1:45:13  Unknown  2016   
5                     8              3.0    8/5/2016 1:45:39  Unknown  2016   
6                     8              3.0    8/5/2016 1:49:21  Unknown  2016   
7                    10              3.0    8/8/2016 1:30:34  Unknown  2016   
8                    10              3.0    8/8/2016 1:33:45  Unknown  2016   
9                    10              3.0    8/8/2016 1:49:29  Unknown  2016   
10                    6              3.0    8/8/2016 1:51:00  Unknown  2016   
11                    6              4.0   7/31/2016 1:04:57  Unknown  2016   
12                    8              3.0   7/31/2016 3:38:14  Unknown  2016   
13                    8              1.0   7/31/2016 3:59:43  Unknown  2016   
14                    8              2.0   7/31/2016 4:19:51  Unknown  2016   
15                   10              4.0   7/31/2016 5:14:20  Unknown  2016   
16                    6              3.0   7/31/2016 6:50:12  Unknown  2016   
17                   10              5.0  7/31/2016 15:23:52  Unknown  2016   
18                    8              2.0  7/31/2016 16:49:45  Unknown  2016   
19                    6              4.0    8/1/2016 1:18:47  Unknown  2016   
20                   10              3.0    8/1/2016 1:30:17  Unknown  2016   
21                   10              3.0    8/1/2016 1:30:17  Unknown  2016   
22                    8              4.0    8/1/2016 6:15:10  Unknown  2016   
23                    8              3.0    8/1/2016 7:56:08  Unknown  2016   
24                    4              3.0  6/23/2016 22:24:53  Unknown  2016   
25                    4              3.0   6/27/2016 4:03:03  Unknown  2016   
26                    6              3.0  6/23/2016 22:13:04  Unknown  2016   
27                    8              4.0  6/23/2016 22:09:23  Unknown  2016   
28                    8              4.0  6/23/2016 22:11:39  Unknown  2016   
29                    8              4.0  6/23/2016 22:11:44  Unknown  2016   
..                  ...              ...                 ...      ...   ...   
961                   9              0.0        9/7/16 12:26     Apps  2016   
962                  10              0.0        9/7/16 12:48     Apps  2016   
963                  10              0.0        9/7/16 13:10    Intro  2016   
964                   9              0.0        9/7/16 14:40     Apps  2016   
965                  10              0.0        9/7/16 14:54     Apps  2016   
966                   8              0.0        9/7/16 15:58     Apps  2016   
967                  10              0.0        9/7/16 17:21     Apps  2016   
968                   9              0.0        9/7/16 19:25       VR  2016   
969                   7              0.0        9/7/16 19:26     Apps  2016   
970                  10              0.0        9/7/16 19:40     Apps  2016   
971                  10              0.0        9/7/16 19:57    Games  2016   
972                  10              0.0         9/8/16 0:00    Intro  2016   
973                   8              0.0         9/8/16 0:58     Apps  2016   
974                  10              0.0         9/8/16 1:59    Games  2016   
975                   7              0.0         9/8/16 6:04     Apps  2016   
976                  10              0.0        9/8/16 14:27    Games  2016   
977                   8              0.0        9/8/16 22:06    Games  2016   
978                   8              0.0        9/8/16 22:20     Apps  2016   
979                  10              0.0        9/8/16 

In [78]:
len(final_df[(final_df['Track'] == 'Apps') & (final_df['week'] == 6)])

35

# CHECKPOINT : Cleaned 2016 Dataset

In [79]:
final_df.to_csv('SA_2016_week_1_8.csv', index=False)

# Clean up 2017 Dataset

In [80]:
FILEPATH_2017 = "SA_Feedback_Surveys_FINAL/2017/Student_Feedback_Surveys-Superview.csv"
df_2017 = pd.read_csv(FILEPATH_2017)
df_2017.Week.unique()

array(['Week 1', 'Week 2', 'Week 7', 'Week 3', 'Week 4', 'Week 5',
       'Week 6', 'Week 8'], dtype=object)

In [81]:
week_mapper = {
    'Week 1': 1,
    'Week 2': 2,
    'Week 3': 3,
    'Week 4': 4,
    'Week 5': 5,
    'Week 6': 6,
    'Week 7': 7,
    'Week 8': 8,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
    6: 6,
    7: 7,
    8: 8
}

df_2017["Week"] = df_2017["Week"].map(week_mapper)

In [83]:
df_2017.Location.unique()

array(['San Francisco', 'Los Angeles', nan, 'New York City',
       'Redwood City', 'Santa Clara', 'Oakland', 'Washington DC',
       'Chicago', 'Atlanta', 'Hong Kong', 'Beijing', 'Tokyo'],
      dtype=object)

In [88]:
location_mapper = {
    'San Francisco': 'SF', 
    'Los Angeles': 'LA', 
    'nan': 'Unspecified',
    'New York City': 'NY',
    'Redwood City': 'RD', 
    'Santa Clara': 'SC', 
    'Oakland': 'OAK', 
    'Washington DC': 'DC',
    'Chicago': 'CHI', 
    'Atlanta': 'ATL', 
    'Hong Kong': 'HK', 
    'Beijing': 'BEI', 
    'Tokyo': 'TK',
    'TK': 'TK',
    'BEI': 'BEI',
    'HK': 'HK',
    'ATL': 'ATL',
    'CHI': 'CHI',
    'DC': 'DC',
    'OAK': 'OAK',
    'SC': 'SC',
    'RD': 'RD',
    'NY': 'NY',
    'Unspecified': 'Unspecified',
    'LA': 'LA',
    'SF': 'SF'   
}

df_2017["Location"] = df_2017["Location"].map(location_mapper)

In [91]:
df_2017['Track'].unique()

array(['Apps, Explorer', 'Apps', 'Games', nan, 'VR', 'Games, Explorer'],
      dtype=object)

In [ ]:
track_mapper = {
    'Apps': 'Apps', 
    'Games': 'Games', 
    'nan': 'Unknown',
    'VR': 'VR',
    'Apps, Explorer': 'Apps, Explorer', 
    'Games, Explorer': 'Games, Explorer',
    'Unknown': 'Unknown'   
}

df_2017["Location"] = df_2017["Location"].map(location_mapper)